version: "3"

services:
  app:
    image: market-engine-api
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.development
    ports:
      - "8080:8080"
